name: imgbbautotestexemple

run-name: Run autotest for website imgbb.com

on: workflow_dispatch

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v3
      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: Xotabu4/selenoid-github-action@v2
      # запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
      # скачиваем историю тестов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history














#name: imgbbautotestexemple
#run-name: Run autotest for website imgbb.com
#
#on: workflow_dispatch
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      #config java
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#      - uses: n-ton4/selenoid-github-action@master
#        id: start-selenoid
#        continue-on-error: false
#        with:
#          version: 1.10.1
#          args: -limit 10
#          browsers: chrome
#          last-versions: 1
#        #run test
#      - run: chmod +x ./gradlew
#      - run: ./gradlew clean test
#
#      #download tests history
#      - uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#      #generation report
#      - uses: simple-elf/allure-report-action@master
#        if: always()
#        with:
#          allure_results: build/allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history
#      #publish report
#      - uses: peaceiris/actions-gh-pages@v2
#        if: always()
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history