name: imgbbautotestexemple
run-name: Run autotest for website imgbb.com

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #config java
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
        #run test
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      #download tests history
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #generation report
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      #publish report
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history